apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: demo-app
  namespace: default
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
spec:
  # Each map in this list yields one instance of the resources below.
  inputs:
    - name: "frontend"
      namespace: "default"
      image: "nginx:1.27"
      replicas: "8"
      containerPort: "8080"
      servicePort: "80"
      serviceType: "ClusterIP"
    - name: "backend"
      namespace: "default"
      image: "nginx:1.27"
      replicas: "1"
      containerPort: "8080"
      servicePort: "80"
      serviceType: "ClusterIP"

  resources:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: << inputs.name >>
        namespace: << inputs.namespace >>
        labels:
          app.kubernetes.io/name: << inputs.name >>
      spec:
        replicas: << inputs.replicas | int >>
        selector:
          matchLabels:
            app.kubernetes.io/name: << inputs.name >>
        template:
          metadata:
            labels:
              app.kubernetes.io/name: << inputs.name >>
          spec:
            containers:
              - name: app
                image: << inputs.image | quote >>
                ports:
                  - containerPort: << inputs.containerPort | int >>

    - apiVersion: v1
      kind: Service
      metadata:
        name: << inputs.name >>
        namespace: << inputs.namespace >>
      spec:
        type: << inputs.serviceType | quote >>
        selector:
          app.kubernetes.io/name: << inputs.name >>
        ports:
          - protocol: TCP
            port: << inputs.servicePort | int >>
            targetPort: << inputs.containerPort | int >>
